version: '3'
services:
  nagios:
    image: nagios-alerta
    hostname: nagios
    container_name: nagios
    ports:
      - 80:80

  alerta:
    image: alerta/alerta-web
    hostname: alerta
    container_name: alerta
    ports: 
      - 8080:8080
    environment:
      - DATABASE_URL=mongodb://alerta-db:27017/monitoring
      - PLUGINS=logstash
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=6379
      - AUTH_REQUIRED=False
      - ADMIN_USERS=admin@alerta.loc
      - ADMIN_PASSWORD=poodle

  alerta-db:
    image: mongo:4.0.19-xenial
    hostname: alerta-db
    container_name: alerta-db

  logstash:
    image: logstash:7.8.1
    hostname: logstash
    container_name: logstash
    volumes:
      - './logstash:/usr/share/logstash/pipeline'
